/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class custom_Pack_Emitter_OscillatingEmitter */

#ifndef _Included_custom_Pack_Emitter_OscillatingEmitter
#define _Included_custom_Pack_Emitter_OscillatingEmitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     custom_Pack_Emitter_OscillatingEmitter
 * Method:    updateEmitter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_custom_Pack_Emitter_OscillatingEmitter_updateEmitter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
