/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class custom_Pack_Emitter_Emitter */

#ifndef _Included_custom_Pack_Emitter_Emitter
#define _Included_custom_Pack_Emitter_Emitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     custom_Pack_Emitter_Emitter
 * Method:    getVelocities
 * Signature: ()[[F
 */
JNIEXPORT jobjectArray JNICALL Java_custom_Pack_Emitter_Emitter_getVelocities
  (JNIEnv *, jobject);

/*
 * Class:     custom_Pack_Emitter_Emitter
 * Method:    updateEmitter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_custom_Pack_Emitter_Emitter_updateEmitter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
